/**
 * Web Routes — Content API
 *
 * /api/storyboard, /api/video/create, /api/video/analyze
 * /api/image/generate, /api/image/describe
 * /video/:jobId/download
 */

import { FastifyInstance } from "fastify";
import * as fs from "fs";
import jwt from "jsonwebtoken";
import crypto from "crypto";
import { prisma } from "@/config/database";
import { UserService } from "@/services/user.service";
import { VideoService } from "@/services/video.service";
import { enqueueVideoGeneration } from "@/config/queue";
import { generateStoryboard, NICHES } from "@/services/video-generation.service";
import { getVideoCreditCostAsync, getImageCreditCostAsync } from "@/config/pricing";
import { ImageGenerationService } from "@/services/image.service";
import { logger } from "@/utils/logger";
import { getConfig } from "@/config/env";
import { validateUrl } from "@/utils/url-validator";
import { generationLimiter } from "@/middleware/rateLimit";
import { ProviderError } from '@/utils/app-errors';
import { getUser } from "./middleware";

function getJwtSecret(): string {
  return getConfig().JWT_SECRET!;
}

export async function contentRoutes(server: FastifyInstance): Promise<void> {
  // ── POST /api/storyboard ──
  server.post("/api/storyboard", async (request, reply) => {
    try {
      const { niche, duration: durationStr, customPrompt } = request.body as Record<string, string>;
      if (!niche || !durationStr)
        return reply.status(400).send({ error: "Niche and duration required" });
      const duration = Number(durationStr);
      const nicheConfig = (NICHES as Record<string, { styles?: string[] }>)[niche];
      const scenes = nicheConfig
        ? Math.max(3, Math.min(Math.floor(duration / 5), 8))
        : 4;
      const storyboard = generateStoryboard(
        niche,
        nicheConfig?.styles?.slice(0, 2) || ["viral"],
        duration,
        scenes,
      );
      return {
        scenes: storyboard.map((s: Record<string, unknown>, i: number) => ({
          scene: i + 1,
          duration: (s.duration as number) || Math.floor(duration / storyboard.length),
          description: customPrompt
            ? `${customPrompt} — ${s.description}`
            : s.description,
        })),
        caption: `🎬 ${niche?.toUpperCase()} video | ${duration}s | Generated by BerkahKarya AI`,
        hashtags: [`#${niche}`, "#AIVideo", "#BerkahKarya", "#ViralContent"],
      };
    } catch (error) {
      server.log.error({ error }, "Storyboard error");
      return reply.status(500).send({ error: "Failed to generate storyboard" });
    }
  });

  // ── POST /api/video/create ──
  server.post("/api/video/create", { preHandler: [generationLimiter] }, async (request, reply) => {
    const user = await getUser(request, reply);
    if (!user) return;
    try {
      const {
        niche, style, duration, customPrompt, storyboard,
        platform = "tiktok", enableVO = true, enableSubtitles = true,
        language = "id", referenceImageUrl, noWatermark, subtitles, voiceover,
      } = request.body as Record<string, string>;

      if (!niche || !duration)
        return reply.status(400).send({ error: "niche and duration required" });

      if (referenceImageUrl) {
        try { validateUrl(referenceImageUrl); }
        catch (urlErr) { return reply.status(400).send({ error: (urlErr as Error).message }); }
      }

      const creditCost = await getVideoCreditCostAsync(Number(duration));
      if (Number(user.creditBalance) < creditCost) {
        return reply.status(402).send({
          error: `Insufficient credits. Need ${creditCost}, have ${user.creditBalance}`,
        });
      }

      await UserService.deductCredits(user.telegramId, creditCost);

      const jobId = `WEB-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;
      const scenes = Array.isArray((storyboard as unknown as Record<string, unknown>)?.scenes)
        ? (storyboard as unknown as Record<string, unknown>).scenes as Array<{ scene: number; duration: number; description: string }>
        : [];
      const sceneData = scenes.length > 0
        ? scenes
        : [{ scene: 1, duration: Number(duration), description: customPrompt || `${niche} marketing video` }];

      try {
        await prisma.video.create({
          data: {
            userId: user.telegramId, jobId, niche, platform,
            duration: Number(duration), scenes: sceneData.length, status: "processing",
            creditsUsed: creditCost,
            storyboard: sceneData as unknown as Parameters<typeof prisma.video.create>[0]['data']['storyboard'],
            styles: style ? [style] : [],
            generationMetadata: {
              noWatermark: noWatermark === 'true',
              subtitles: subtitles !== 'false',
              voiceover: enableVO !== 'false' || voiceover !== 'false',
            },
          },
        });

        await enqueueVideoGeneration({
          jobId, niche, platform, duration: Number(duration),
          scenes: sceneData.length, storyboard: sceneData,
          customPrompt: customPrompt || undefined,
          referenceImage: referenceImageUrl || undefined,
          userId: user.telegramId.toString(), chatId: Number(user.telegramId),
          enableVO: enableVO === 'true', enableSubtitles: enableSubtitles === 'true', language,
        });
      } catch (jobError) {
        await UserService.refundCredits(user.telegramId, creditCost, jobId, (jobError as Error)?.message || "job creation failed")
          .catch((err) => logger.error("Refund failed", { error: err.message }));
        throw jobError;
      }

      return { ok: true, jobId, message: "Video generation started" };
    } catch (error) {
      server.log.error({ error }, "Video create error");
      return reply.status(500).send({ error: "Failed to create video" });
    }
  });

  // ── POST /api/video/analyze ──
  server.post("/api/video/analyze", async (request, reply) => {
    const user = await getUser(request, reply);
    if (!user) return;
    try {
      const { videoUrl } = request.body as Record<string, string>;
      if (!videoUrl) return reply.status(400).send({ error: "videoUrl is required" });
      try { validateUrl(videoUrl); }
      catch (urlErr) { return reply.status(400).send({ error: (urlErr as Error).message }); }

      const { VideoAnalysisService } = await import("@/services/video-analysis.service.js");
      const result = await VideoAnalysisService.analyze(videoUrl);

      if (!result.success) {
        return reply.status(422).send({ error: result.error || "Analysis failed" });
      }

      return {
        ok: true, niche: result.niche, style: result.style,
        totalDuration: result.totalDuration, transcript: result.transcript,
        storyboard: result.storyboard,
        hasKeyFrames: (result.keyFramePaths?.length || 0) > 0,
      };
    } catch (error) {
      server.log.error({ error }, "Video analyze error");
      return reply.status(500).send({ error: "Failed to analyze video" });
    }
  });

  // ── POST /api/image/generate ──
  server.post("/api/image/generate", { preHandler: [generationLimiter] }, async (request, reply) => {
    const user = await getUser(request, reply);
    if (!user) return;
    try {
      const { prompt, category = "general", style, aspectRatio = "1:1", referenceImageUrl, avatarImageUrl } = request.body as Record<string, string>;
      if (!prompt) return reply.status(400).send({ error: "prompt is required" });

      for (const url of [referenceImageUrl, avatarImageUrl]) {
        if (url) { try { validateUrl(url); } catch (urlErr) { return reply.status(400).send({ error: (urlErr as Error).message }); } }
      }

      const IMAGE_CREDIT_COST = await getImageCreditCostAsync();
      if (Number(user.creditBalance) < IMAGE_CREDIT_COST) {
        return reply.status(402).send({ error: `Insufficient credits. Need ${IMAGE_CREDIT_COST}, have ${user.creditBalance}` });
      }

      await UserService.deductCredits(user.telegramId, IMAGE_CREDIT_COST);

      let result;
      try {
        result = await ImageGenerationService.generateImage({ prompt, category, style, aspectRatio, referenceImageUrl, avatarImageUrl });
      } catch (genError) {
        await UserService.refundCredits(user.telegramId, IMAGE_CREDIT_COST, `IMG-REFUND-${Date.now()}`, (genError as Error)?.message || "exception")
          .catch((err) => logger.error("Refund failed", { error: err.message }));
        throw genError;
      }

      if (!result.success) {
        await UserService.refundCredits(user.telegramId, IMAGE_CREDIT_COST, `IMG-REFUND-${Date.now()}`, result.error || "Generation failed");
        return reply.status(500).send({ error: result.error || "Image generation failed" });
      }

      return { ok: true, imageUrl: result.imageUrl, provider: result.provider };
    } catch (error) {
      server.log.error({ error }, "Image generate error");
      return reply.status(500).send({ error: "Failed to generate image" });
    }
  });

  // ── POST /api/image/describe ──
  server.post("/api/image/describe", async (request, reply) => {
    const user = await getUser(request, reply);
    if (!user) return;
    try {
      const { imageUrl } = request.body as Record<string, string>;
      if (!imageUrl) return reply.status(400).send({ error: "imageUrl is required" });
      try { validateUrl(imageUrl); } catch (urlErr) { return reply.status(400).send({ error: (urlErr as Error).message }); }

      const { ContentAnalysisService } = await import("@/services/content-analysis.service.js");
      const result = await ContentAnalysisService.extractPrompt(imageUrl, "image");

      if (!result.success) {
        return reply.status(422).send({ error: result.error || "Could not analyze image" });
      }

      return { ok: true, description: result.prompt, style: result.style, elements: result.elements };
    } catch (error) {
      server.log.error({ error }, "Image describe error");
      return reply.status(500).send({ error: "Failed to describe image" });
    }
  });

  // ── GET /video/:jobId/download ──
  server.get("/video/:jobId/download", async (request, reply) => {
    try {
      const { jobId } = request.params as { jobId: string };
      const { token } = request.query as { token?: string };
      if (!token) return reply.status(401).send({ error: "Missing token" });

      let payload: jwt.JwtPayload;
      try { payload = jwt.verify(token, getJwtSecret()) as jwt.JwtPayload; }
      catch { return reply.status(401).send({ error: "Invalid token" }); }
      if (payload.jobId !== jobId) return reply.status(403).send({ error: "Token mismatch" });

      const video = await VideoService.getByJobId(jobId);
      if (!video) return reply.status(404).send({ error: "Video not found" });
      if (video.userId.toString() !== payload.telegramId)
        return reply.status(403).send({ error: "Access denied" });

      const localPath = video.downloadUrl;

      if (localPath && fs.existsSync(localPath)) {
        const filename = `berkahkarya-${jobId}.mp4`;
        const stream = fs.createReadStream(localPath);
        const stat = fs.statSync(localPath);
        reply.header("Content-Type", "video/mp4");
        reply.header("Content-Disposition", `attachment; filename="${filename}"`);
        reply.header("Content-Length", stat.size);
        return reply.send(stream);
      }

      if (video.videoUrl) {
        try {
          const providerRes = await fetch(video.videoUrl);
          if (!providerRes.ok) throw new ProviderError("upstream", `Upstream fetch failed: ${providerRes.status}`);
          const filename = `berkahkarya-${jobId}.mp4`;
          reply.header("Content-Type", "video/mp4");
          reply.header("Content-Disposition", `attachment; filename="${filename}"`);
          const contentLength = providerRes.headers.get("content-length");
          if (contentLength) reply.header("Content-Length", contentLength);
          return reply.send(providerRes.body);
        } catch { /* fall through to 404 */ }
      }

      return reply.status(404).send({ error: "Video file is no longer available. Please regenerate the video." });
    } catch (error) {
      server.log.error({ error }, "Video download error");
      return reply.status(500).send({ error: "Download failed" });
    }
  });
}
