"""
Comic/Manga/Manhwa data models.

Shared types for the generation pipeline.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class ComicFormat(Enum):
    """Target format for the output."""
    COMIC = "comic"       # Western comic: LTR, color, 4-9 panels/page
    MANGA = "manga"       # Japanese manga: RTL, B&W, 3-7 panels/page
    MANHWA = "manhwa"     # Korean webtoon: scroll, color, 1-3 panels/page


class PanelShape(Enum):
    WIDE = "wide"         # 16:9-ish landscape
    SQUARE = "square"     # 1:1
    TALL = "tall"         # 4:5-ish portrait
    FULL = "full"         # full page width (webtoon)


@dataclass
class Character:
    name: str
    role: str                # protagonist, antagonist, side, etc.
    appearance: str          # physical description
    personality: str         # personality traits
    color_scheme: str = ""   # key colors (for color formats)


@dataclass
class SpeechBubble:
    speaker: str
    text: str
    position_hint: str = "auto"   # auto, top, bottom, left, right


@dataclass
class Panel:
    panel_id: int
    shape: PanelShape = PanelShape.SQUARE
    scene_description: str = ""       # visual scene description (for image gen)
    narration: str = ""                # narration / caption text
    dialogue: list[SpeechBubble] = field(default_factory=list)
    character_positions: str = ""     # where characters are in frame
    background: str = ""              # background / environment
    action: str = ""                  # action / movement
    mood: str = ""                    # mood / atmosphere key


@dataclass
class Page:
    page_number: int
    panels: list[Panel] = field(default_factory=list)
    layout_type: str = "auto"     # auto, grid, staggered, splash, webtoon


@dataclass
class Episode:
    episode_number: int
    title: str = ""
    pages: list[Page] = field(default_factory=list)
    summary: str = ""


@dataclass
class ComicScript:
    """Full comic/manga/manhwa script generated by the LLM."""
    title: str
    format: ComicFormat
    language: str
    synopsis: str
    characters: list[Character] = field(default_factory=list)
    episodes: list[Episode] = field(default_factory=list)
    style_notes: str = ""         # art style / visual direction
    cover_description: str = ""


@dataclass
class RenderedPage:
    """Output of the composition step: one page as an image."""
    page_number: int
    image_bytes: bytes
    format: str = "PNG"
    width: int = 0
    height: int = 0
