"""
Movie / short-film data models.

Shared types for the generation pipeline.
Mirrors the comic_gen pattern, specialized for film/video output.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class MovieGenre(Enum):
    SHORT_FILM = "short_film"
    DOCUMENTARY = "documentary"
    MUSIC_VIDEO = "music_video"
    AD = "ad"
    EXPLAINER = "explainer"
    TUTORIAL = "tutorial"


class SceneType(Enum):
    LIVE_ACTION = "live_action"
    ANIMATED = "animated"
    SLIDESHOW = "slideshow"
    AI_GENERATED = "ai_generated"


@dataclass
class Character:
    name: str
    role: str                     # protagonist, narrator, interviewee, etc.
    description: str              # appearance and personality
    voice: str = ""               # voice actor / TTS voice preference


@dataclass
class Shot:
    """A single camera shot within a scene."""
    shot_id: int
    description: str              # visual description (camera, framing, action)
    narration: str = ""           # voiceover / dialogue for this shot
    camera_movement: str = ""     # static, pan, zoom, dolly, etc.
    duration_seconds: float = 3.0
    mood: str = ""                # lighting / color mood
    sound_effect: str = ""        # foley / SFX


@dataclass
class Scene:
    """A single scene in the movie."""
    scene_id: int
    title: str
    description: str              # visual scene description
    narration: str = ""           # voiceover / narrator text for this scene
    location: str = ""            # setting / location
    characters: list[str] = field(default_factory=list)  # character names present
    shots: list[Shot] = field(default_factory=list)
    mood: str = ""
    bg_music_mood: str = ""       # suggested background music feel
    duration_seconds: float = 5.0


@dataclass
class MovieScript:
    """Full movie / short-film script generated by the LLM."""
    title: str
    genre: MovieGenre = MovieGenre.SHORT_FILM
    language: str = "en"
    logline: str = ""
    synopsis: str = ""
    characters: list[Character] = field(default_factory=list)
    scenes: list[Scene] = field(default_factory=list)
    style_notes: str = ""         # visual style / cinematography direction
    target_duration_seconds: float = 60.0


@dataclass
class RenderedScene:
    """Output of the image/video generation step: one scene as media."""
    scene_id: int
    image_path: str               # path to generated scene image
    audio_path: str = ""          # path to TTS narration audio
    video_path: str = ""          # path to rendered video segment
    duration_seconds: float = 5.0


@dataclass
class MovieOutput:
    """Final assembled movie output."""
    title: str
    video_path: str               # path to final MP4
    duration_seconds: float
    total_scenes: int
    format: str = "mp4"
    resolution: str = "1920x1080"
    output_dir: str = ""
